System:
  name: Mask Detection Application
  NetworkDomains:
    ND1:
      name: Network Domain 1
      AccessDelay: 2.77e-06
      Bandwidth: 40000
      subNetworkDomains: []
      ComputationalLayers:
        computationalLayer1:
          name: Private cloud Layer
          number: 1
          type: Virtual
          Resources:
            resource1:
              name: VM1
              totalNodes: 6
              description: g5.2xlarge
              cost: 1.2
              memorySize: 8192
              storageSize: 100
              storageType: SSD
              operatingSystemDistribution: Ubuntu
              operatingSystemType: Linux
              operatingSystemVersion: 20.04
              operatingSystemImageId: aws://eu-west-1/ami-0b4cbe13ae8c9ea8f
              secureBoot: false
              measuredBoot: false
              onSpot: false
              processors:
                processor1:
                  name: Xeon
                  type: SkyLake
                  architecture: amd64
                  computingUnits: 4
                  internalMemory: 64
                  SGXFlag: false
    ND2:
      name: Network Domain 2
      AccessDelay: 2.77e-06
      Bandwidth: 40000
      subNetworkDomains:
      - ND1
      ComputationalLayers:
        computationalLayer2:
          name: Public Cloud Layer
          number: 2
          type: Virtual
          Resources:
            resource2:
              name: VM3
              totalNodes: 6
              description: g5.2xlarge
              cost: 1.2
              memorySize: 8192
              storageSize: 100
              storageType: SSD
              operatingSystemDistribution: Ubuntu
              operatingSystemType: Linux
              operatingSystemVersion: 20.04
              operatingSystemImageId: aws://eu-west-1/ami-0b4cbe13ae8c9ea8f
              secureBoot: false
              measuredBoot: false
              onSpot: false
              processors:
                processor1:
                  name: Xeon
                  type: SkyLake
                  architecture: amd64
                  computingUnits: 8
                  internalMemory: 64
                  SGXFlag: false
  Components:
    component1:
      name: blurry-faces-onnx-test2
      executionLayer: 1
      Containers:
        container1:
          image: docker.io/nhikoherz/blurry-faces-onnx-test2:tag
          memorySize: 2048
          computingUnits: 0.9
          trustedExecution: false
          networkProtection: false
          fileSystemProtection: false
          GPURequirement: false
          selectedExecutionResources: VM1
    component2:
      name: mask-detector-test2
      executionLayer: 2
      Containers:
        container1:
          image: docker.io/nhikoherz/mask-detector-test2:tag
          memorySize: 4096
          computingUnits: 0.9
          trustedExecution: false
          networkProtection: false
          fileSystemProtection: false
          GPURequirement: false
          selectedExecutionResources: VM3
